In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [40]:
df = pd.read_csv('elevate_activities_export.2023.8.2-11.27.23.csv')
df.head()

,Date,Type,Moving Time,Distance (km),Elevation Gain (m),Avg Speed (kph),Avg Pace (/km),Calories,Grade Adj. Pace (/km),Best 20min Pace (/km),...,HRSS / h,Best 20min HR (bpm),Best 60min HR (bpm),σ HR (bpm),Avg Watts (w),Avg W / Kg (w/kg),Normalized Power® (w),NP® / Kg (w/kg),Best 20min Power (w),Delete
0,2023-08-02T12:56:14.000Z,Run,37:55,5.1,9,8.1,07:24,441,07:25,07:20,...,66,157,-,6,177,2.36,178,2.38,178,NaN
1,2023-08-01T20:04:42.000Z,Ride,01:36:44,35.0,130,21.7,02:46,828,-,02:17,...,57,160,149,12,90,1.20,146,1.94,121,NaN
2,2023-07-31T18:54:55.000Z,Ride,01:14:54,24.8,101,19.9,03:01,579,-,02:35,...,43,147,142,12,74,1.00,130,1.76,99,NaN
3,2023-07-31T13:58:36.000Z,Run,53:18,7.0,15,7.9,07:34,584,07:34,07:19,...,54,150,-,7,172,2.32,173,2.33,176,NaN
4,2023-07-30T15:51:01.000Z,Run,29:48,4.0,3,8.0,07:27,315,07:30,07:18,...,61,156,-,11,174,2.36,178,2.40,176,NaN

In [52]:
df['Date'] = pd.to_datetime(df['Date']).dt.date

TypeError: <class 'pandas._libs.tslibs.timedeltas.Timedelta'> is not convertible to datetime

In [42]:
dfRun = df[df['Type'] == 'Run']
dfRide = df[df['Type'] == 'Ride']

# dfRun.info()
# dfRide.info()

In [43]:
dfRun.describe()

,Distance (km),Elevation Gain (m),Avg Speed (kph),Calories,Avg HR (bpm),Max HR (bpm),Hrss,HRSS / h,Best 20min HR (bpm),σ HR (bpm),Avg Watts (w),Avg W / Kg (w/kg),Normalized Power® (w),NP® / Kg (w/kg),Best 20min Power (w),Delete
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,0.0
mean,5.144444,9.222222,8.022222,411.444444,152.666667,166.777778,39.444444,62.777778,156.222222,8.000000,172.222222,2.324444,174.444444,2.351111,176.555556,NaN
std,1.322035,8.969083,0.405518,114.088903,4.415880,7.870479,7.907451,6.591240,4.437842,2.345208,8.120618,0.109329,8.017342,0.106236,8.001736,NaN
min,3.800000,3.000000,7.400000,289.000000,146.000000,155.000000,30.000000,53.000000,150.000000,5.000000,160.000000,2.160000,161.000000,2.170000,165.000000,NaN
25%,4.100000,3.000000,7.800000,315.000000,151.000000,163.000000,33.000000,59.000000,155.000000,6.000000,166.000000,2.240000,172.000000,2.320000,173.000000,NaN
50%,5.100000,4.000000,8.000000,399.000000,153.000000,166.000000,41.000000,63.000000,156.000000,8.000000,174.000000,2.360000,178.000000,2.380000,176.000000,NaN
75%,5.400000,12.000000,8.300000,441.000000,156.000000,170.000000,43.000000,68.000000,158.000000,9.000000,177.000000,2.390000,178.000000,2.400000,182.000000,NaN
max,7.500000,30.000000,8.700000,598.000000,158.000000,181.000000,53.000000,71.000000,164.000000,12.000000,185.000000,2.500000,187.000000,2.520000,190.000000,NaN